### ISSUE TITLE
example7

### ISSUE THREAD

**Issue by tochange** [HJ-Money/MTransition#1]
窗帘，如果带有actionbar，reverse动画完成之后会闪屏

**Comment by HJ-Money** [comment]
请问是界面闪烁还是发生位移？

**Comment by tochange** [comment]
界面, 方便的话加个微信聊聊，tochange_

**Comment by HJ-Money** [comment]
如微信沟通，该问题解决方案是setContainer传递时要传递包含ActionBar的ContainerView；
但库也需要做个更好的优化，去优化这种有ActionBar的情况。
